.server:
  port: 9090
spring:
  application:
    name: product-service
  cloud:
    stream:
      bindings:
        inventory-in-0:
          group: '${spring.application.name}'
          content-type: application/json
          destination: inventory-group
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false
inventary:
  host: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true