spring:
  application:
    name: inventory-service
  cloud:
    stream:
      bindings:
        operation-in-0:
          group: '${spring.application.name}'
          content-type: application/json
          destination: operation-group
        operation-out-0:
          content-type: application/json
          destination: inventory-group
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
    listener:
      missing-topics-fatal: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true